### PR TITLE
Upload images to ImgurAPI

### PR DESCRIPTION
**Pull request by alorma**

### CODE REVIEW

**Comment by alorma** [comment]
Test message

**Comment by GeorgeWL** [comment]
Pity that the github as API doesn't really have any support for image upload, cause I'd rather imgur didn't get even more money from the adverts.

**Comment by GeorgeWL** [comment]
I'd say maybe having it as a choice would work,  so when click upload it gives option of :

A) upload from http link 

B) upload from device

**Comment by alorma** [comment]
What you mean? I won't may it payment feature. And Imgur API is free

**Comment by alorma** [comment]
Yes, that's what i'm planning

**Comment by GeorgeWL** [comment]
Imgur have started doing some despicable advertising practices such as replacing direct links with adverts on initial load then after a few seconds loading the image.

**Comment by alorma** [comment]
Mmmmm, i haven't noticied that. I will be aware of it, thanks.

What other services you recommend for image upload?

**Comment by GeorgeWL** [comment]
So, is this now coming with the next update?

**Comment by alorma** [comment]
Not yet, i have some bugs that need to be fixed before

**Pull request merged**
