### PR TITLE
Big Presenters architecture refactoring

### PR DESCRIPTION
**Pull request by LetItRock**
Refactoring:
- implemented model: http://creately.com/diagram/itg268ss2/6mpVATzY0Q0JklJxDw2YJeg0%3D
- cleaned up presenters architecture
- used Dagger for dependency injection for changed presenters

### CODE REVIEW

**Comment by LetItRock** [comment]
Activities/Fragments need to test (I did that but you know it would be better if you do that also :P ) :
- CommitDetailActivity
- CurrentAccountReposFragment
- IssueDetailActivity
- IssueLabelsActivity
- MembershipReposFragment
- NavigationFragment
- NotificationsFragment
- OrgsReposFragment
- RepoDetailActivity
- ReposFragmentFromOrgs
- RepositoryMilestonesActivity
- RepositoryTagsFragment
- StarredReposFragment
- UserIssuesListFragment
- UsernameReposFragment
- WatchedReposFragment

**Comment by alorma** [comment]
88 changed files
2,314 additions and 1,119 deletions

O_o, looks good!

**Comment by alorma** [comment]
- [x] CommitDetailActivity
- [x] CurrentAccountReposFragment
- [x] IssueDetailActivity
- [x] IssueLabelsActivity
- [x] MembershipReposFragment
- [x] NavigationFragment
- [x] NotificationsFragment
- [x] OrgsReposFragment
- [x] RepoDetailActivity
- [x] ReposFragmentFromOrgs
- [x] RepositoryMilestonesActivity
- [x] RepositoryTagsFragment
- [x] StarredReposFragment
- [x] UserIssuesListFragment
- [x] UsernameReposFragment
- [x] WatchedReposFragment

**Comment by alorma** [comment]
Everything works fine

**Review by alorma — APPROVED** [review]

**Pull request merged**
